### ISSUE TITLE
Numerical values as permissions

### ISSUE THREAD

**Issue by Martmists-GH** [lucko/fabric-permissions-api#2]
How does this support permissions like `homes.limit.X` and similar?

**Comment by lucko** [comment]
It doesn't - permission based (true/false/undefined) checks only for now.

**Comment by martmists-gh** [comment]
Are there plans to add this or will that have to wait for an official permission API for fabric?

**Comment by lucko** [comment]
Added in https://github.com/lucko/fabric-permissions-api/commit/997c4c78731b3d5af204864786d8b3b8a10ee4db
