### ISSUE TITLE
Incompatibility with Carpet Mod Fake Players

### ISSUE THREAD

**Issue by DillonB07** [lucko/fabric-permissions-api#3]
This API is incompatible with [Carpet Mod](https://github.com/gnembon/fabric-carpet) and it’s /player command.
Could you please fix this? Many of the mods I like use this API and I can’t use those mods because of this incompatibility.
Or at least I can’t use permissions with them.

**Comment by lucko** [comment]
Could you explain what the incompatibility is?

**Comment by DillonB07** [comment]
Currently testing it. I'll send a log when done.

**Comment by DillonB07** [comment]
[paste.ee/p/Rt7Np/](https://paste.ee/p/Rt7Np/)
That is a log of what happens when you run the command.
I removed LuckPerms and all mods with this API and it worked fine.

**Comment by DillonB07** [comment]
Sorry I was wrong. The incompatibility was with LuckPerms not the API.

**Comment by SpaceClouds42** [comment]
It's not the api's fault.
Source of bug is [this line](https://github.com/lucko/LuckPerms/blob/82488140ee6556aa41f20a89d92d31559f6904ba/fabric/src/main/java/me/lucko/luckperms/fabric/listeners/PermissionCheckListener.java#L67), in LuckPerms

**Comment by lucko** [comment]
Thanks, should be fixed now in LuckPerms
