### ISSUE TITLE
[Suggestion] Vanilla Permissions

### ISSUE THREAD

**Issue by DillonB07** [lucko/fabric-permissions-api#4]
Is there any chance that you would support vanilla permissions such as `/op` or `/trigger` so that we can customise everyone's permissions without the different levels of op?

**Comment by DillonB07** [comment]
Any plans for that or an ETA?
I don't want to be one of the people that say `Do this!` so I'm just curious if there are plans or if it is underway.

**Comment by lucko** [comment]
I have no current plans to do it myself, but can't speak for anyone else obviously :p

**Comment by LoganDark** [comment]
https://github.com/LoganDark/fabric-command-hider is a thing now. It depends on an unreleased version of Fabric Loader though (for now), and it only does commands. It does all commands though, including modded ones like LP's (great for removing those pesky legacy `/perms` commands).

**Comment by LoganDark** [comment]
The version of Fabric Loader that Command Hider requires has been out for a bit now, so it works on real installations.
