### ISSUE TITLE
Possible to shade? 

### ISSUE THREAD

**Issue by heychazza** [lucko/fabric-permissions-api#8]
Hey luck,

Is there any chance you're able to allow shading the library, as my mod seems to throw errors when I attempt to shade it.

**Comment by lucko** [comment]
With Fabric, you should include dependency mods as a jar-in-jar instead of shading them. 

I have updated the docs to give an example of how to do this: https://github.com/lucko/fabric-permissions-api/blob/master/USAGE.md#adding-the-dependency

Hope that helps :)
